workflows:
    ios-workflow:
      name: iOS AutoSign Workflow
      environment:
        groups:
          - code-signing
        vars:
          XCODE_PROJECT: "Workout detail.xcodeproj" # <-- Put the name of your workspace here.
          XCODE_SCHEME: "Workout Detail" # <-- Put the name of your scheme here.
          BUNDLE_ID: "com.marinahuber.Workout" # <-- Put your Bundle Id here.
          APP_STORE_APPLE_ID: 6741595847 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
        xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      triggering:
        events:
          - push
          - pull_request
        branch_patterns:
          - pattern: 'main'
            include: true
            source: true
      scripts:
        - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
          script: |
            keychain initialize
        - name: Fetch signing files
          script: |
            app-store-connect fetch-signing-files "$(xcode-project detect-bundle-id)" \
            --type IOS_APP_STORE \
            --create
        - name: Use system default keychain
          script: |
            keychain add-certificates
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        - name: Increment build number
          script: |
            # agvtool new-version -all $(($BUILD_NUMBER + 1))
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      integrations:
        app_store_connect: Codemagic Appstore Key
